return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  branch = 'main',
  build = ':TSUpdate',
  config = function(_, opts)
    local ensure_installed = {
      'bash',
      'c',
      'cangjie',
      'cmake',
      'cpp',
      'css',
      'csv',
      'dockerfile',
      'editorconfig',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'glsl',
      'gnuplot',
      'go',
      'goctl',
      'gomod',
      'gosum',
      'gowork',
      'graphql',
      'hlsl',
      'html',
      'http',
      'hyprlang',
      'ini',
      'javascript',
      'jsdoc',
      'json',
      'json5',
      'latex',
      'llvm',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'mermaid',
      'meson',
      'nginx',
      'ninja',
      'proto',
      'python',
      'qmljs',
      'regex',
      'ron',
      'rust',
      'sql',
      'ssh_config',
      'svelte',
      'toml',
      'typescript',
      'udev',
      'vim',
      'vimdoc',
      'wgsl',
      'wgsl_bevy',
      'xml',
      'yaml',
    }

    require('nvim-treesitter').install(ensure_installed)
  end,
}
