return { 
	"nvim-treesitter/nvim-treesitter", 
	branch = 'master', 
	lazy = false, 
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"arduino",
				"asm",
				"bash",
				"c",
				"c_sharp",
				"cmake",
				"cpp",
				"css",
				"csv",
				"dart",
				"dockerfile",
				"editorconfig",
				"elixir",
				"elm",
				"fish",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"glsl",
				"gnuplot",
				"go",
				"goctl",
				"gomod",
				"gosum",
				"gowork",
				"graphql",
				"hlsl",
				"html",
				"http",
				"hyprlang",
				"ini",
				"javascript",
				"jsdoc",
				"json",
				"json5",
				"kotlin",
				"latex",
				"llvm",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"mermaid",
				"meson",
				"nginx",
				"ninja",
				"proto",
				"python",
				"regex",
				"ron",
				"rust",
				"sql",
				"ssh_config",
				"svelte",
				"toml",
				"typescript",
				"udev",
				"wgsl",
				"wgsl_bevy",
				"xml",
				"yaml",
			},
			sync_install = false,
      			highlight = { enable = true },
      			indent = { enable = true },
		})
	end
}

